version: '3'

services:
    app: 
        container_name: "reg_index"
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            PORT: ${PORT}
            POSTGRES_HOST: ${POSTGRES_HOST}
        ports:
            - ${PORT}:${PORT}
        depends_on:
            - postgres_db
        networks:
            myapp_net:

    postgres_db:
        image: bitnami/postgresql:15
        container_name: "reg_index_db"
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_TIMEZONE: ${POSTGRES_TIMEZONE}
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - "postgres_data:/bitnami/postgresql"
        networks:
            myapp_net:

volumes:
    postgres_data:

networks:
    myapp_net:
