version: '3'

services:
    app: 
        container_name: "reg_index"
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            PORT: ${PORT}
            POSTGRES_HOST: ${POSTGRES_HOST}
        ports:
            - 3000:3000
        depends_on:
            - postgres_db
        networks:
            myapp_net:

    postgres_db:
        image: postgres
        container_name: "reg_index_db"
        restart: always
        environment:
            POSTGRES_HOST: $POSTGRES_HOST}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        volumes:
            - "postgres:/var/lib/postgresql/data"
        networks:
            myapp_net:

volumes:
    postgres:

networks:
    myapp_net:
